/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#005e73',
        'on-primary-fixed-variant': '#2d476f',
        tertiary: '#321b00',
        'on-secondary-fixed': '#001f27',
        'surface-bright': '#f9f9ff',
        'on-background': '#121c2c',
        'tertiary-container': '#4f2e00',
        'primary-container': '#1a365d',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#86a0cd',
        'on-primary-fixed': '#001b3c',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        surface: '#f9f9ff',
        'inverse-primary': '#adc7f7',
        'on-tertiary-fixed-variant': '#633f0f',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#adc7f7',
        'tertiary-fixed-dim': '#f2bc82',
        secondary: '#00677d',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#b3ebff',
        'on-surface': '#121c2c',
        background: '#f9f9ff',
        'on-surface-variant': '#43474e',
        primary: '#002045',
        'secondary-container': '#63dbfe',
        'surface-container-highest': '#d9e3f9',
        'surface-variant': '#d9e3f9',
        'outline-variant': '#c4c6cf',
        'inverse-surface': '#273141',
        'on-error': '#ffffff',
        'primary-fixed': '#d6e3ff',
        'surface-container-high': '#dee8ff',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#2b1700',
        'surface-container-low': '#f0f3ff',
        'on-tertiary-container': '#c6955e',
        'tertiary-fixed': '#ffddba',
        'surface-dim': '#d0daf0',
        outline: '#74777f',
        'surface-container': '#e7eeff',
        'surface-tint': '#455f88',
        'inverse-on-surface': '#ebf1ff',
        'secondary-fixed-dim': '#5cd5f8',
        'on-secondary-fixed-variant': '#004e5f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        'container-max': '1200px',
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
};
